### ISSUE TITLE
サポートされる Matrix の形について

### ISSUE THREAD

**Issue by kariya-mitsuru** [Kasugaccho/DungeonTemplateLibrary#10]
サポートされる Matrix の形について質問があります。
Matrix は完全に四角形のみサポートされるのでしょうか？
それとも、行によって長さが異なる形もサポートされるのでしょうか？

**Comment by AsPJT** [comment]
https://github.com/Kasugaccho/DungeonTemplateLibrary/wiki/Matrix%E3%81%AE%E7%A8%AE%E9%A1%9E
ここで説明されているSTL系またはレイヤーSTL系のみ長さが異なる型もサポートされています。
ただし、完全な四角形のみサポートされている地形生成クラスがあるのでご注意ください。

現時点で行によって長さが異なる形が使用できる地形生成クラスは以下の通りです。
・Border
・BorderOdd
~・CellularAutomatonIsland~
~・CellularAutomatonMixIsland~
・HalfMixRect
・MixRect
・PointGrid
・PointGridAndSomeBlocksWithBorder
・PointGridWithBorder
・RandomRect
・Rect

ただし、現時点では詳しい検証が取れていないものが多いため
不具合がある可能性が高いです。

**Comment by kariya-mitsuru** [comment]
ご回答ありがとうございました。
