### ISSUE TITLE
CMake対応

### ISSUE THREAD

**Issue by yumetodo** [Kasugaccho/DungeonTemplateLibrary#15]
`./MSVC`以下がmasterから消え去ったらPull Requestを投げつける

**Comment by AsPJT** [comment]
`./MSVC`以下がmasterから消え去りました。

**Comment by Kasugaccho** [comment]
完全に消え去りました。

**Comment by yumetodo** [comment]
よっしゃ、やるわ。金曜日か土曜日くらいには作業終わると良いなぁ

**Comment by yumetodo** [comment]
@Kasugaccho 
`Sample`の中をdirectory分けしたいのです。つまり

- Reference
  - Sample
    - *.cpp

から

- sample
  - Shape
    - *.cpp
  - Storage
    - *.cpp
  - etc

としたいです。

理由

- `shape_`のようなprefixをつけるくらいならdirectoryを分けるべき
- `sample`がtop levelになくてReference以下にあるのは直感的ではない

**Comment by AsPJT** [comment]
確かにそうですね。
ということで `Sample` フォルダはトップに、
プレフィックスはフォルダとして生まれ変わりました。

**Comment by yumetodo** [comment]
@Kasugaccho `include`と`Sample`で命名規則がガバガバでは？

**Comment by AsPJT** [comment]
ちゃんと命名規則があるのでガバガバではないと思いますが、どの辺がガバガバでしょうか。

**Comment by yumetodo** [comment]
いまいちどういう命名規則かわからないのです。

- include
  - DTL
    - Shape
    - Storage
- sample
  - Shape
  - Storage

てっきりこういうふうになるのだと思ってました。

**Comment by Kasugaccho** [comment]
あー！DTLフォルダの存在をすっかり忘れていました……。
しばらく外出していて直せないので、勝手に直して頂いても大丈夫です。
(そのままになっていたら帰ってから直します)

**Comment by AsPJT** [comment]
DTLフォルダを作成しました。

**Comment by yumetodo** [comment]
ちょっと立て込んでいたので作業できてませんでした。

ところで

- include
  - DTL
    - Shape
    - Storage
- Sample
  - DTL
    - shape
    - storage

となったようですが、実に面白い命名規則ですね！ということでこのまま作業を進めます、CMake対応には直接関係ないので。

**Comment by AsPJT** [comment]
- include
  - DTL
    - Shape
    - Storage
- Sample
  - DTL
    - Shape
    - Storage

へ変更しました。
(includeフォルダ以外のフォルダ名が小文字になっているのはバグです)

**Comment by yumetodo** [comment]
>(includeフォルダ以外のフォルダ名が小文字になっているのはバグです)

??

**Comment by AsPJT** [comment]
includeフォルダ以外のフォルダは、
フォルダ名を先頭は大文字でそろえているので
ミスでした。

**Comment by yumetodo** [comment]
あ、治りましたね。本格的に作業に取り掛かります。
