### ISSUE TITLE
Dungeon/ImageWrite.hppとは？

### ISSUE THREAD

**Issue by yumetodo** [Kasugaccho/DungeonTemplateLibrary#16]
`/Sample/DTL/Storage`以下の全ファイルについて

```cpp
#include <Dungeon/ImageWrite.hpp>
```

とあるが

```cpp
#include <DTL/ImageWrite.hpp>
```
ではないか？

**Comment by AsPJT** [comment]
修正ミスです。修正しました。
報告ありがとうございます。
https://github.com/Kasugaccho/DungeonTemplateLibrary/commit/fce5e46a36ce0be052002a6c0bd83cb9dd185709

**Comment by yumetodo** [comment]
確認しました。
