### ISSUE TITLE
dtl::storage::FileMD: 書き出しファイルの拡張子はtxtではなくmdであるべきではないか？

### ISSUE THREAD

**Issue by yumetodo** [Kasugaccho/DungeonTemplateLibrary#17]
# 問題

`/Sample/DTL/Storage/FileMD.cpp`は

```cpp
dtl::storage::FileMD<shape_t>("file_sample.txt").write(matrix);
```

のように書かれています。名前的にMarkdownじゃないかとおもうのですが、すると拡張子は`.txt`ではなく`.md`が妥当ではないでしょうか？

# 動機

cmake からビルドしたサンプルを走らせるときに、実行前にこれで生成するファイル名を削除するようにする予定である ( #15 ) 。この際に`/Sample/DTL/Storage/FileMD.cpp`だけコンパイルするファイル名(`file[A-Z]+.cpp`)のパターンに引っかからない拡張子が採用されている。例外処理を書くのがだるいので差し障りがなければこっちを書き換えて対処したい

**Comment by AsPJT** [comment]
変更しました。
https://github.com/Kasugaccho/DungeonTemplateLibrary/commit/e48ecd0809bb9f50590bd8eb0f7cd1021c45bf62

**Comment by yumetodo** [comment]
ありがとうございます。
