### ISSUE TITLE
CIを有効にする

### ISSUE THREAD

**Issue by yumetodo** [Kasugaccho/DungeonTemplateLibrary#19]
せっかく #18 でcmakeに対応したので、まだ単体テストはないけど、CIでビルドができることを保証したい。

**Comment by yumetodo** [comment]
@Kasugaccho どのCIがお好みですかね？

**Comment by AsPJT** [comment]
@yumetodo 
何でもよいですよ。
(CIについてあまり詳しくないので……)

TravisCI、CircleCIくらいしか存じていないです。

**Comment by yumetodo** [comment]
というよりはどのコンパイラで検証したいかですね。

ちなみに各OSのパッケージマネージャで落ちてくるデフォルトは

- CentOS/RedHat
  - CentOS7
    - gcc 4.8.5
    - clang 3.4.2 
- Ubuntu
  - Ubuntu 18.04(bionic-updates)
    - gcc 7.4,0
    - clang 6.0
  - Ubuntu 16.04
    - gcc 5.3.1
    - clang 3.8
- debian(stable)
  - gcc 6.3.0
  - clang 3.8
- ArchLinux(core)
  - gcc 8.3.0
  - clang 8.0.0

です。gcc 4.8.5 とかclang 3.4とかって`-std=c++1y`とかしていた時代ですね。やばい。
CentOS/RedHat 5や6もまだ生きているので頭がいたいですね。

**Comment by AsPJT** [comment]
検証するとしたらClangが良いですね。特になるべく最新のもの。
そうすると、ArchLinux(core) か Ubuntu 18.04 ですかね。

**Comment by yumetodo** [comment]
古いコンパイラは対応しない方針ということで良いでしょうか？ユーザーが常に最新のコンパイラを使ってくれるとは限りませんが。

**Comment by AsPJT** [comment]
古いコンパイラもサポートしたいです。
特に最低でもGCC4.8以上、Clang3.8以上で動作を保証したいです。

新しい環境だと古い環境をサポート出来ないことを忘れていました。

**Comment by yumetodo** [comment]
GCC4.8ってC++14対応してないですが、C++11でコンパイル通るんでしたっけ？

**Comment by AsPJT** [comment]
当ライブラリはC++11も動作を保証しています。
(ちゃんと動きます)

ちなみにREADMEにきちんと書いてあります。

**Comment by yumetodo** [comment]
ぐえっ、cmake直してこないと・・・

**Comment by yumetodo** [comment]
>当ライブラリはC++11も動作を保証しています。

なおC++14の機能が紛れていた模様。
eb0ba386f99e4560b506c60632fe7e7fc4555c2b

下限を決定してほしいです。gccとclangのどのバージョンがどんな機能に対応しているかは
https://cpprefjp.github.io/implementation-status.html
にまとまっています。
Clang3.8はC++11という意味ではちょっと新しい気がします。

**Comment by AsPJT** [comment]
下限は
Clangは3.3、GCCは4.8が理想ですかね。

ちなみに今のバージョンだと
Clang3.3はコケますね。

**Comment by AsPJT** [comment]
> なおC++14の機能が紛れていた模様。

まさかC++14の機能が残っていたなんて……。
(手元のコンパイラはエラーも警告も出ませんでした)

**Comment by AsPJT** [comment]
Clang 3.6.0まで現時点での対応バージョンを下げました。
https://github.com/Kasugaccho/DungeonTemplateLibrary/commit/2cbb1f69d0c0627e43ca80d3ff2df61cc1635eb1

もっと下げたいですがClang 3.5.0でえげつないエラーが……。

**Comment by yumetodo** [comment]
CIそのものは有効になっているので後は #36 で・・・。
