### ISSUE TITLE
開発ブランチとリリースブランチを分けてほしい

### ISSUE THREAD

**Issue by ai2playgame** [Kasugaccho/DungeonTemplateLibrary#23]
件のUE4対応のときに、開発ブランチとリリースブランチが別れておらず、少々しんどい思いをしたので、最低限ブランチを分けてほしい（タグ付けはしているようですが）

**Comment by AsPJT** [comment]
確かに開発branchとリリースbranchは分けるべきですね。
今から分けて運用していきます。
