### ISSUE TITLE
Unused parameterがたくさんある

### ISSUE THREAD

**Issue by loliGothicK** [Kasugaccho/DungeonTemplateLibrary#3]
`clang++-8 -std=c++17 -Wall -Wextra`でコンパイルすると大量のunused parameter警告が出る。
修正すべきかもしれない。

**Comment by loliGothicK** [comment]
詳しいエラーメッセージは長いので[gist](https://gist.github.com/LoliGothick/c25153fc1210888442dc4e0db3135cea)の方に貼りましたので参照していただきたい。

**Comment by AsPJT** [comment]
こんなにエラーが出るのですね……。
(手元のVS2017 + Clang 8.0で全ての警告ONにしてもこんなには出ません……)

**Comment by AsPJT** [comment]
確かにunusedが沢山あるのが確認できました。

**Comment by loliGothicK** [comment]
割と不要な変数である気がするんですが、どうなんでしょう？

**Comment by AsPJT** [comment]
不要ですね。
警告が出ていないものは気が付きませんでした。

**Comment by AsPJT** [comment]
こちらで可能な限り直します。

**Comment by AsPJT** [comment]
直しました。

**Comment by loliGothicK** [comment]
関数名は別であるにもかかわらず、使わない引数を取る必要があるのは何故ですか？

**Comment by AsPJT** [comment]
理由は特にないですね。
また、先ほどのunusedを確認したところ本来は使うべきはずの引数が使われていなかったことが大半なので基本的にはミスである可能性が高いです。

**Comment by AsPJT** [comment]
恐らくunusedは全て無くなったと思います。
(こちらの環境では以前と変わらず1つもunused警告が出ていないので憶測ですが……)

**Comment by loliGothicK** [comment]
>先ほどのunusedを確認したところ本来は使うべきはずの引数が使われていなかった

なるほど、理解
