### ISSUE TITLE
複数の翻訳単位からインクルードすると未定義動作となる

### ISSUE THREAD

**Issue by kariya-mitsuru** [Kasugaccho/DungeonTemplateLibrary#31]
MersenneTwister32bit.hpp には複数の static な変数がありますが、これらは inline 関数内で使用されています。
このため、複数の翻訳単位からインクルードすると未定義動作となってしまいます。
（正確には、これらの inline 関数を複数の翻訳単位から使用すると未定義動作となる）

解決方法としては、以下のいずれかになると思います。
1. 複数の翻訳単位から使用することを諦めて、複数の翻訳単位からのインクルードを禁止する。
1. C++17 以降のみ対応として、変数を inline にする。
1. static 変数を諦めて、inline 関数内の static 変数にする。

**Comment by yumetodo** [comment]
関数内にstatic変数を定義してその参照を返せば回避できなかったでしたっけ？

```cpp
int& n(){
    static int n;
    return n;
}
```

**Comment by kariya-mitsuru** [comment]
分かりにくくてすみません、3 がそれを言ったつもりです。

**Comment by yumetodo** [comment]
@kariya-mitsuru ああ、なるほど。

**Comment by AsPJT** [comment]
```cpp
static thread_local test_class a;
```
を
```cpp
inline test_class& a_func(){
    static thread_local test_class a;
    return a;
}
```
と書くようにすれば解決できる感じですか。
そうであれば `a` を `a_func()` へ置換したいと思います。

**Comment by kariya-mitsuru** [comment]
inline 変数が一番スマートですが、関数にすることに問題なければそれで良いと思います。
あと、他にも回避策がありました。

1. C++14 以降のみ対応として、変数テンプレートを使用する。
1. クラステンプレートの static メンバ変数にする。

いろいろあるものですね…

**Comment by kariya-mitsuru** [comment]
それぞれ Wandbox で試した結果です。

inline 変数
https://wandbox.org/permlink/BpHyOuZjCcpVlntt

inline 関数内の static ローカル変数
https://wandbox.org/permlink/Bi3B3QYzBbflHSoe

変数テンプレート
https://wandbox.org/permlink/iQ9T4AoE6ilJnobU

クラステンプレートの static メンバ変数
https://wandbox.org/permlink/VTMk1AMg5pj8nCb7

**Comment by yumetodo** [comment]
変数テンプレートという手が合ったのか、それは知らなかった。

**Comment by yumetodo** [comment]
それはそうと

```cpp
inline test_class& a_func(){
    static thread_local test_class a;
    return a;
}
```

この場合`static thread_local`じゃなくて`thread_local`で良かった気が

**Comment by kariya-mitsuru** [comment]
あっ、そうですね

**Comment by AsPJT** [comment]
`クラステンプレートの static メンバ変数`
の仕様に変更しました。
