### ISSUE TITLE
使用されている乱数エンジンに seed sequence を渡せない

### ISSUE THREAD

**Issue by kariya-mitsuru** [Kasugaccho/DungeonTemplateLibrary#32]
MersenneTwister32bit.hpp に乱数エンジンが提供されていますが、こちらのクラスに seed sequence を渡すことができません。
メルセンヌツイスターの内部状態は非常に大きいため、seed に単一の整数のみしか渡せないのはちょっと残念です。

http://www.pcg-random.org/posts/cpp-seeding-surprises.html

ちなみに、std::random_device を std::seed_seq で使用する例がこちらに載っています。
https://codereview.stackexchange.com/questions/109260/seed-stdmt19937-from-stdrandom-device

**Comment by AsPJT** [comment]
実装している乱数クラスの設計は不十分だと思っているので、より拡張性のある実装にしていきたいと思います。

**Comment by AsPJT** [comment]
std::seed_seqを渡せるように変更しました。
